build:
  image: golang:1.5
  environment:
    - GO15VENDOREXPERIMENT=1
    - GOOS=linux
    - GOARCH=amd64
    - CGO_ENABLED=0
  commands:
    - make deps
    - make build
    - make test

publish:
  coverage:
    when:
      branch: master
  docker:
    username: drone
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: plugins/drone-coverage
    when:
      branch: master

plugin:
  name: Coverage
  desc: Aggregate and publish coverage reports.
  type: publish
  image: plugins/drone-coverage
  labels:
    - coverage
    - reporting
    - lcov
    - simplecov
